In [ ]:
import json
from google.colab import files
uploaded = files.upload()

In [ ]:
file_name = "something.json"
# io.StringIO[file_name].decode("utf-8")

In [ ]:
json.loads(uploaded[file_name].decode("utf-8"))

In [ ]:
data = json.loads(uploaded[file_name].decode("utf-8"))

In [ ]:
import pandas as pd
import numpy as np
# create dataframe
df = pd.json_normalize(data)
# save to csv
# df.to_csv('submission.csv', index=False, encoding='utf-8')
df

                                         annotations
0  [{'category_id': 34, 'iscrowd': 0, 'image_id':...

In [ ]:
df.to_csv('something.csv', index=False)

In [ ]:
new_df = df
new_df['image_id'] = new_df['filename']
for i in range(0,new_df['filename'].size) :
  new_df['image_id'].iloc[i] = new_df['filename'].iloc[i].split('/')[1]
new_df.drop(['filename','frame_id'],axis = 1)

/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)

                                               objects                                           image_id
0    [{'class_id': 7, 'name': 'suv', 'relative_coor...  Asraf_51_jpg.rf.0e3516baf7509bc2c4a4aa8deea494...
1    [{'class_id': 6, 'name': 'minivan', 'relative_...  Asraf_52_jpg.rf.867869f276e6db3a09a84b99643df3...
2    [{'class_id': 6, 'name': 'minivan', 'relative_...  Asraf_50_jpg.rf.7026694f0b9f37a6790982295c7e86...
3    [{'class_id': 7, 'name': 'suv', 'relative_coor...  sabiha(134)_jpg.rf.ba07ab0848d138f35911948f0ab...
4    [{'class_id': 11, 'name': 'bicycle', 'relative...  sabiha(125)_jpg.rf.2cabe489c259c4cae597c2c77eb...
..                                                 ...                                                ...
495  [{'class_id': 8, 'name': 'van', 'relative_coor...  Shykat_5_ (99)_jpg.rf.77dadbce8b05681b3f945041...
496  [{'class_id': 7, 'name': 'suv', 'relative_coor...  Shykat_5_ (97)_jpg.rf.64d22026d38be7b14963a464...
497  [{'class_id': 8, 'name': 'van', 'relative_coor...  Shykat_5_ (96)_jpg.rf.ba7c1d9f83e80317a6464233...
498  [{'class_id': 4, 'name': 'three_wheelers_(CNG)...  Shykat_5_ (98)_jpg.rf.a7efc4441768d6458e162a86...
499  [{'class_id': 3, 'name': 'car', 'relative_coor...  Shykat_5_ (93)_jpg.rf.62cf351639869f8c04f4255d...

[500 rows x 2 columns]

In [ ]:
value = []
image_id = []
count = 0
for i in range(0,new_df['objects'].size) :
  for j in range(0,len(new_df['objects'].iloc[i])):
    count = count + 1
    value.append(new_df['objects'].iloc[i][j])
    image_id.append(new_df['image_id'].iloc[i])
print(count)

3620

In [ ]:
column = pd.DataFrame({'col':np.arange(count)})
new_df = pd.concat([new_df,column], ignore_index=True, axis=1)
new_df.head(10)

      0  ...  4
0   1.0  ...  0
1   2.0  ...  1
2   3.0  ...  2
3   4.0  ...  3
4   5.0  ...  4
5   6.0  ...  5
6   7.0  ...  6
7   8.0  ...  7
8   9.0  ...  8
9  10.0  ...  9

[10 rows x 5 columns]

In [ ]:
new_df.drop([0,1,2,3],axis = 1,inplace= True)
# new_df

In [ ]:
new_df.insert(0,"image_id",image_id)
new_df.insert(1, "column", value)
new_df.drop([4],axis = 1,inplace = True)
new_df

                                               image_id                                             column
0     Asraf_51_jpg.rf.0e3516baf7509bc2c4a4aa8deea494...  {'class_id': 7, 'name': 'suv', 'relative_coord...
1     Asraf_51_jpg.rf.0e3516baf7509bc2c4a4aa8deea494...  {'class_id': 6, 'name': 'minivan', 'relative_c...
2     Asraf_51_jpg.rf.0e3516baf7509bc2c4a4aa8deea494...  {'class_id': 6, 'name': 'minivan', 'relative_c...
3     Asraf_51_jpg.rf.0e3516baf7509bc2c4a4aa8deea494...  {'class_id': 5, 'name': 'pickup', 'relative_co...
4     Asraf_51_jpg.rf.0e3516baf7509bc2c4a4aa8deea494...  {'class_id': 5, 'name': 'pickup', 'relative_co...
...                                                 ...                                                ...
3615  Shykat_5_ (98)_jpg.rf.a7efc4441768d6458e162a86...  {'class_id': 0, 'name': 'bus', 'relative_coord...
3616  Shykat_5_ (93)_jpg.rf.62cf351639869f8c04f4255d...  {'class_id': 3, 'name': 'car', 'relative_coord...
3617  Shykat_5_ (93)_jpg.rf.62cf351639869f8c04f4255d...  {'class_id': 3, 'name': 'car', 'relative_coord...
3618  Shykat_5_ (93)_jpg.rf.62cf351639869f8c04f4255d...  {'class_id': 1, 'name': 'rickshaw', 'relative_...
3619  Shykat_5_ (93)_jpg.rf.62cf351639869f8c04f4255d...  {'class_id': 1, 'name': 'rickshaw', 'relative_...

[3620 rows x 2 columns]

In [ ]:

bbox_value = pd.DataFrame(new_df.column.values.tolist())['relative_coordinates']
bbox_value = pd.DataFrame.from_records(bbox_value)
bbox_value

      left_x  top_y  width  height
0        582    673     31      58
1        501    653     65     144
2        644    664     56      47
3        930    565     95     164
4        533    644     40      81
...      ...    ...    ...     ...
3615     565    685    160     223
3616     218    641     74     102
3617     527    640     54      80
3618     100    812    109     227
3619     330    635     31      83

[3620 rows x 4 columns]

In [ ]:
#Formatting the Dataframe
class_name = []
score = []
for i in range(new_df['column'].size):
  class_name.append(new_df['column'].iloc[i]['name'])
  score.append(new_df['column'].iloc[i]['confidence'])
new_df.insert(1,"name",class_name)
new_df.insert(3, "score", score)
new_df = pd.concat([new_df,bbox_value],ignore_index=True, axis = 1)
new_df = new_df.rename(columns={0: "image_id", 1: "class", 3: "score", 4: "xmin", 5: "ymax", 6: "width", 7: "height"})
new_df.drop([2],axis = 1,inplace = True)
new_df['xmax'] = new_df['xmin'] + new_df['width']
new_df['ymin'] = new_df['ymax'] - new_df['height']
new_df.drop(['width','height'],axis = 1,inplace = True)
new_df['width'] = pd.Series([1024 for x in range(len(new_df.index))])
new_df['height'] = pd.Series([1024 for x in range(len(new_df.index))])
new_df = new_df[["image_id","class","score","xmin","ymin","xmax","ymax","width","height"]]
for i in range(new_df['xmax'].size):
  if new_df['xmax'].iloc[i] > 1024:
    new_df['xmax'].iloc[i] = 1024;
for i in range(new_df['ymax'].size):
  if new_df['ymax'].iloc[i] > 1024:
    new_df['ymax'].iloc[i] = 1024;
for i in range(new_df['class'].size):
  if new_df['class'].iloc[i] == "three_wheelers_(CNG)":
    new_df['class'].iloc[i] = "three wheelers (CNG)"
  if new_df['class'].iloc[i] == "human_hauler":
    new_df['class'].iloc[i] = "human hauler"
  if new_df['class'].iloc[i] == "auto_rickshaw":
    new_df['class'].iloc[i] = "auto rickshaw"
  if new_df['class'].iloc[i] == "army_vehicle":
    new_df['class'].iloc[i] = "army vehicle"
new_df

/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)

                                               image_id  ... height
0     Asraf_51_jpg.rf.0e3516baf7509bc2c4a4aa8deea494...  ...   1024
1     Asraf_51_jpg.rf.0e3516baf7509bc2c4a4aa8deea494...  ...   1024
2     Asraf_51_jpg.rf.0e3516baf7509bc2c4a4aa8deea494...  ...   1024
3     Asraf_51_jpg.rf.0e3516baf7509bc2c4a4aa8deea494...  ...   1024
4     Asraf_51_jpg.rf.0e3516baf7509bc2c4a4aa8deea494...  ...   1024
...                                                 ...  ...    ...
3615  Shykat_5_ (98)_jpg.rf.a7efc4441768d6458e162a86...  ...   1024
3616  Shykat_5_ (93)_jpg.rf.62cf351639869f8c04f4255d...  ...   1024
3617  Shykat_5_ (93)_jpg.rf.62cf351639869f8c04f4255d...  ...   1024
3618  Shykat_5_ (93)_jpg.rf.62cf351639869f8c04f4255d...  ...   1024
3619  Shykat_5_ (93)_jpg.rf.62cf351639869f8c04f4255d...  ...   1024

[3620 rows x 9 columns]

In [ ]:
new_df.to_csv('submission.csv',index = False)